// حساباتي v5 — توزيع ذكي للدخل مع الحفاظ على بيانات v4
let transactions=[], installments=[], fixedExpenses=[], goals=[], currentType='income', currentCycleOnly=false;
const SETTINGS_KEY='myFinanceSettings', TRANSACTIONS_KEY='myFinanceTransactions', INSTALLMENTS_KEY='myFinanceInstallments', FIXED_KEY='myFinanceFixedExpenses', GOALS_KEY='myFinanceGoals', ENVELOPES_KEY='myFinanceEnvelopes';
const defaultSettings={cycleStartDay:30,lesson:{gold:25,emergency:20,investment:15,goals:20,fun:10,reserve:10},other:{gold:15,emergency:20,investment:15,goals:20,fun:10,reserve:20}};
let envelopes={gold:0,emergency:0,investment:0,goals:0,fun:0,reserve:0};
const money=n=>Number(n||0).toLocaleString('ar-EG')+' ج.م';
function esc(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function dateInput(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function localDate(v){let [y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)}
function fmtDate(d){return new Date(d).toLocaleDateString('ar-EG',{day:'numeric',month:'short',year:'numeric'})}
function getSettings(){try{return {...defaultSettings,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return defaultSettings}}
function saveAll(){localStorage.setItem(TRANSACTIONS_KEY,JSON.stringify(transactions));localStorage.setItem(INSTALLMENTS_KEY,JSON.stringify(installments));localStorage.setItem(FIXED_KEY,JSON.stringify(fixedExpenses));localStorage.setItem(GOALS_KEY,JSON.stringify(goals));localStorage.setItem(ENVELOPES_KEY,JSON.stringify(envelopes))}
function load(){try{transactions=JSON.parse(localStorage.getItem(TRANSACTIONS_KEY)||'[]');installments=JSON.parse(localStorage.getItem(INSTALLMENTS_KEY)||'[]');fixedExpenses=JSON.parse(localStorage.getItem(FIXED_KEY)||'[]');goals=JSON.parse(localStorage.getItem(GOALS_KEY)||'[]');envelopes={...envelopes,...JSON.parse(localStorage.getItem(ENVELOPES_KEY)||'{}')}}catch{};populateSettings();document.getElementById('transactionDate').value=dateInput(new Date());renderAll()}
function cycle(date){let s=getSettings(),day=s.cycleStartDay,d=new Date(date);d.setHours(0,0,0,0);let y=d.getFullYear(),m=d.getMonth();if(d.getDate()<Math.min(day,new Date(y,m+1,0).getDate()))m--;if(m<0){m=11;y--}let start=new Date(y,m,Math.min(day,new Date(y,m+1,0).getDate())),ny=y,nm=m+1;if(nm>11){nm=0;ny++}let next=new Date(ny,nm,Math.min(day,new Date(ny,nm+1,0).getDate()));let end=new Date(next);end.setDate(end.getDate()-1);return{start,end}}
function inCycle(date,c){let d=new Date(date);d.setHours(0,0,0,0);return d>=c.start&&d<=c.end}
function allocationFor(category,amount){let s=getSettings(), p=category==='دروس'?s.lesson:s.other;return Object.fromEntries(Object.entries(p).map(([k,v])=>[k,amount*Number(v||0)/100]))}
const labels={gold:'🪙 الذهب',emergency:'🛟 الطوارئ',investment:'📈 الاستثمار',goals:'🎯 الأهداف',fun:'🎉 الترفيه',reserve:'💰 الاحتياطي'};
function renderAllocation(amount,category){let a=allocationFor(category,amount);document.getElementById('allocationPreview').innerHTML=Object.entries(a).map(([k,v])=>`<div class="allocation-row"><span>${labels[k]}</span><strong>${money(v)}</strong></div>`).join('');document.getElementById('incomeAllocationBox').classList.toggle('hidden',!amount)}
function renderEnvelopes(){document.getElementById('envelopes').innerHTML=Object.entries(labels).map(([k,l])=>`<div class="envelope"><span>${l}</span><strong>${money(envelopes[k])}</strong></div>`).join('')}
function renderPlan(){let salary=transactions.filter(t=>t.type==='income'&&t.category==='مرتب').reduce((s,t)=>s+Number(t.amount),0),lessons=transactions.filter(t=>t.type==='income'&&t.category==='دروس').reduce((s,t)=>s+Number(t.amount),0),fixed=fixedExpenses.reduce((s,x)=>s+Number(x.amount),0)+installments.reduce((s,x)=>s+Math.max(0,x.total-x.paid)*0,0);let c=cycle(new Date()),cycleSalary=transactions.filter(t=>t.type==='income'&&t.category==='مرتب'&&inCycle(new Date(t.date),c)).reduce((s,t)=>s+Number(t.amount),0);let msg=cycleSalary?`المرتب المسجل للدورة: <b>${money(cycleSalary)}</b> — الالتزامات الثابتة المسجلة: <b>${money(fixed)}</b>. التطبيق يحجز الالتزامات أولًا.`:`لم تسجل مرتب الدورة الحالية بعد. عند نزوله سجله كـ <b>مرتب</b> ليحسب لك المتاح.`;document.getElementById('planSummary').innerHTML=`<div class="plan-box">${msg}<div class="plan-stats"><span>إجمالي المرتب<br><b>${money(salary)}</b></span><span>إجمالي الدروس<br><b>${money(lessons)}</b></span></div></div>`}
function renderGoals(){let el=document.getElementById('goalsList');if(!goals.length){el.innerHTML='<p class="empty">أضف أول هدف: سفر، شراء، خروجة…</p>';return}el.innerHTML=goals.map(g=>{let pct=Math.min(100,(Number(g.saved||0)/Number(g.target))*100);return `<div class="goal"><div class="goal-top"><strong>${esc(g.name)}</strong><span>${money(g.saved||0)} / ${money(g.target)}</span></div><div class="bar-track"><div class="bar-fill" style="width:${pct}%"></div></div><small>${pct.toFixed(0)}% مكتمل <button class="small-btn" onclick="deleteGoal('${g.id}')">حذف</button></small></div>`}).join('')}
function renderFixed(){let el=document.getElementById('fixedExpensesList');if(!fixedExpenses.length){el.innerHTML='<p class="empty">أضف مصروف البيت، الأقساط، العلاج، الكهرباء، الغاز، المياه، الإنترنت…</p>';return}el.innerHTML=fixedExpenses.map(x=>`<div class="fixed-row"><div><strong>${esc(x.name)}</strong><small>${x.priority==='essential'?'🔴 ضروري':'🟠 مهم'}</small></div><strong>${money(x.amount)}</strong><button class="small-btn" onclick="deleteFixed('${x.id}')">حذف</button></div>`).join('')}
function renderDashboard(){let c=cycle(new Date()),ti=0,te=0,ci=0,ce=0;transactions.forEach(t=>{let a=Number(t.amount)||0;if(t.type==='income'){ti+=a;if(inCycle(new Date(t.date),c))ci+=a}else{te+=a;if(inCycle(new Date(t.date),c))ce+=a}});[['balance',ti-te],['totalIncome',ti],['totalExpense',te],['cycleIncome',ci],['cycleExpense',ce]].forEach(([id,v])=>document.getElementById(id).textContent=money(v));document.getElementById('cycleTitle').textContent=`${fmtDate(c.start)} → ${fmtDate(c.end)}`)}
function renderTransactions(){let el=document.getElementById('transactionsList'),c=cycle(new Date()),d=[...transactions].sort((a,b)=>new Date(b.date)-new Date(a.date));if(currentCycleOnly)d=d.filter(t=>inCycle(new Date(t.date),c));if(!d.length){el.innerHTML='<p class="empty">لا توجد عمليات</p>';return}el.innerHTML=d.map(t=>`<div class="transaction"><div><strong>${esc(t.category)}</strong><div class="muted">${esc(t.note||'بدون ملاحظة')} • ${fmtDate(t.date)}</div><div class="transaction-actions"><button onclick="editTransaction('${t.id}')">✏️ تعديل</button><button class="delete" onclick="deleteTransaction('${t.id}')">🗑️ حذف</button></div></div><strong class="${t.type==='income'?'income':'expense'}">${t.type==='income'?'+':'-'}${money(t.amount)}</strong></div>`).join('')}
function renderInstallments(){let el=document.getElementById('installmentsList');if(!installments.length){el.innerHTML='<p class="empty">لا توجد أقساط مضافة</p>';return}el.innerHTML=installments.map(i=>{let r=Math.max(0,i.total-i.paid);return `<div class="installment"><div class="installment-top"><strong>${esc(i.name)}</strong><strong>${money(i.amount)}</strong></div><div class="installment-meta">يستحق يوم ${i.day}<br>المدفوع: ${i.paid} من ${i.total} • المتبقي: ${r}<br>إجمالي المتبقي: ${money(r*i.amount)}</div>${r?`<button class="pay-btn" onclick="payInstallment('${i.id}')">💳 سداد القسط القادم</button>`:'<div class="muted">✅ تم الانتهاء</div>'}<button class="small-btn" onclick="deleteInstallment('${i.id}')">حذف</button></div>`}).join('')}
function renderAll(){renderDashboard();renderPlan();renderEnvelopes();renderGoals();renderFixed();renderInstallments();renderTransactions()}
function showForm(type,edit=null){currentType=type;let c=document.getElementById('category');c.innerHTML=type==='income'?'<option>مرتب</option><option>دروس</option><option>دخل آخر</option>':'<option>أكل</option><option>مواصلات</option><option>فواتير</option><option>أقساط</option><option>تسوق</option><option>ترفيه</option><option>أخرى</option>';let f=document.getElementById('formSection');f.classList.remove('hidden');document.getElementById('formTitle').textContent=edit?'تعديل العملية':type==='income'?'إضافة دخل':'إضافة مصروف';if(edit){document.getElementById('amount').value=edit.amount;c.value=edit.category;document.getElementById('note').value=edit.note||'';document.getElementById('transactionDate').value=dateInput(new Date(edit.date));f.dataset.editId=edit.id}else{document.getElementById('amount').value='';document.getElementById('note').value='';document.getElementById('transactionDate').value=dateInput(new Date());delete f.dataset.editId}document.getElementById('incomeAllocationBox').classList.toggle('hidden',type!=='income');document.getElementById('amount').oninput=()=>type==='income'&&renderAllocation(Number(document.getElementById('amount').value),c.value);c.onchange=()=>type==='income'&&renderAllocation(Number(document.getElementById('amount').value),c.value);if(type==='income'&&!edit)renderAllocation(0,c.value);f.scrollIntoView({behavior:'smooth'})}
function closeForm(){document.getElementById('formSection').classList.add('hidden')}
function saveTransaction(){let a=Number(amount.value),cat=category.value,note=document.getElementById('note').value.trim(),dv=transactionDate.value,f=document.getElementById('formSection');if(a<=0||!dv)return alert('أدخل المبلغ والتاريخ بشكل صحيح');let date=localDate(dv),id=f.dataset.editId;if(id){let i=transactions.findIndex(t=>String(t.id)===String(id));if(i>=0)transactions[i]={...transactions[i],amount:a,type:currentType,category:cat,note,date:date.toISOString()};showToast('تم تعديل العملية')}else{transactions.push({id:Date.now(),amount:a,type:currentType,category:cat,note,date:date.toISOString()});if(currentType==='income'){let al=allocationFor(cat,a);Object.keys(al).forEach(k=>envelopes[k]+=al[k]);showToast('تم الحفظ وتوزيع الدخل على الأظرف')}else showToast('تم حفظ المصروف')}saveAll();closeForm();renderAll()}
function editTransaction(id){let t=transactions.find(x=>String(x.id)===String(id));if(t)showForm(t.type,t)}
function deleteTransaction(id){if(!confirm('حذف العملية؟'))return;transactions=transactions.filter(t=>String(t.id)!==String(id));saveAll();renderAll();showToast('تم حذف العملية')}
function showCurrentCycleOnly(){currentCycleOnly=!currentCycleOnly;renderTransactions()}
function openGoalForm(){document.getElementById('goalForm').classList.remove('hidden');document.getElementById('goalForm').scrollIntoView({behavior:'smooth'})}function closeGoalForm(){document.getElementById('goalForm').classList.add('hidden')}
function saveGoal(){let n=goalName.value.trim(),t=Number(goalTarget.value);if(!n||t<=0)return alert('أدخل بيانات الهدف');goals.push({id:Date.now(),name:n,target:t,saved:0});saveAll();closeGoalForm();goalName.value='';goalTarget.value='';renderGoals();showToast('تم إضافة الهدف')}
function deleteGoal(id){if(!confirm('حذف الهدف؟'))return;goals=goals.filter(g=>String(g.id)!==String(id));saveAll();renderGoals()}
function openFixedForm(){fixedForm.classList.remove('hidden');fixedForm.scrollIntoView({behavior:'smooth'})}function closeFixedForm(){fixedForm.classList.add('hidden')}
function saveFixedExpense(){let n=fixedName.value.trim(),a=Number(fixedAmount.value),p=fixedPriority.value;if(!n||a<=0)return alert('أدخل بيانات الالتزام');fixedExpenses.push({id:Date.now(),name:n,amount:a,priority:p});saveAll();closeFixedForm();fixedName.value='';fixedAmount.value='';renderAll();showToast('تم إضافة الالتزام')}
function deleteFixed(id){if(!confirm('حذف الالتزام؟'))return;fixedExpenses=fixedExpenses.filter(x=>String(x.id)!==String(id));saveAll();renderAll()}
function openInstallmentForm(){installmentForm.classList.remove('hidden');installmentForm.scrollIntoView({behavior:'smooth'})}function closeInstallmentForm(){installmentForm.classList.add('hidden')}
function saveInstallment(){let n=installmentName.value.trim(),a=Number(installmentAmount.value),d=Number(installmentDay.value),t=Number(installmentTotal.value),p=Number(installmentPaid.value);if(!n||a<=0||d<1||d>31||t<1||p<0||p>t)return alert('راجع بيانات القسط');installments.push({id:Date.now(),name:n,amount:a,day:d,total:t,paid:p});saveAll();closeInstallmentForm();renderAll();showToast('تمت إضافة القسط')}
function payInstallment(id){let i=installments.find(x=>String(x.id)===String(id));if(!i||i.paid>=i.total)return;transactions.push({id:Date.now(),amount:i.amount,type:'expense',category:'أقساط',note:`${i.name} - القسط ${i.paid+1}`,date:new Date().toISOString()});i.paid++;saveAll();renderAll();showToast('تم تسجيل سداد القسط')}
function deleteInstallment(id){if(!confirm('حذف القسط؟'))return;installments=installments.filter(x=>String(x.id)!==String(id));saveAll();renderAll()}
function populateSettings(){let s=getSettings();cycleStartDay.value=s.cycleStartDay;['lesson','other'].forEach(group=>Object.keys(s[group]).forEach(k=>document.getElementById(group==='lesson'?'lesson'+cap(k):'other'+cap(k)).value=s[group][k]))}function cap(s){return s[0].toUpperCase()+s.slice(1)}
function readGroup(prefix){let o={};['gold','emergency','investment','goals','fun','reserve'].forEach(k=>o[k]=Number(document.getElementById(prefix+cap(k)).value)||0);return o}
function validGroup(o){return Object.values(o).reduce((a,b)=>a+b,0)===100}
function openSettings(){populateSettings();settingsPanel.classList.remove('hidden');settingsPanel.scrollIntoView({behavior:'smooth'})}function closeSettings(){settingsPanel.classList.add('hidden')}
function saveSettings(){let day=Number(cycleStartDay.value),lesson=readGroup('lesson'),other=readGroup('other');if(day<1||day>31)return alert('اختر يومًا من 1 إلى 31');if(!validGroup(lesson)||!validGroup(other))return alert('كل مجموعة نسب يجب أن يكون مجموعها 100%');localStorage.setItem(SETTINGS_KEY,JSON.stringify({cycleStartDay:day,lesson,other}));closeSettings();renderAll();showToast('تم حفظ الإعدادات')}
function showToast(m){let t=document.getElementById('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2000)}
load();
